### ISSUE TITLE
Enums are not available when running non-legacy build

### ISSUE THREAD

**Issue by tomdye** [dojo/cli-build-widget#14]
When running non-legacy build on a widget that imports an enum such as `Keys` from `@dojo/widgets/common/util` the build will fail / warn that `Keys` cannot be found. 

The enum is present in the `.d.ts` file, but does not feature in the `.js` or the `.m.js` in the widget dist.

**Comment by dylans** [comment]
Closed via https://github.com/dojo/widgets/pull/525
