### ISSUE TITLE
Process for creating user widget libraries

### ISSUE THREAD

**Issue by robagar** [dojo/cli-build-widget#19]
Finalise and document the process for developing custom widget libraries.

Ideally with a tutorial describing how to...
* create a new widget library project from scratch
* build using `dojo build widget`, including css and other resources 
* use an unpublished widget library package in a Dojo application using `npm link` or similar

**Comment by agubler** [comment]
hi @robagar, we are looking to address this as part of the roadmap for the next major release.

An issue with specifics has been created here #35

**Comment by agubler** [comment]
This has been completed with the lib type on cli-build-widget.
