### ISSUE TITLE
Replace deprecated postcss-cssnext

### ISSUE THREAD

**Issue by smhigley** [dojo/cli-build-widget#30]
The creator of `cssnext` has bowed out and marked it as [deprecated](https://moox.io/blog/deprecating-cssnext/). It looks like it's being replaced with [postcss-preset-env](https://github.com/csstools/postcss-preset-env).

**Comment by matt-gadd** [comment]
@smhigley we already have an issue for this on meta, https://github.com/dojo/meta/issues/262, so going to close.
