### ISSUE TITLE
Switch away from testing against fixtures

### ISSUE THREAD

**Issue by matt-gadd** [dojo/cli-build-widget#34]
The output fixtures are a nightmare to maintain and are not portable across platforms. We should switch to the way we now test in cli-build-app, and that is to assert that the thing actually works in the browser. see: https://github.com/dojo/cli-build-app/pull/99 and https://github.com/dojo/cli-build-app/blob/master/tests/integration/build.spec.ts

**Comment by agubler** [comment]
resolved by #48
